{% set name = "vector-classes" %}
{% set version = "1.4.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/VcDevel/Vc/archive/refs/tags/{{ version }}.tar.gz
  sha256: eb734ef4827933fcd67d4c74aef54211b841c350a867c681c73003eb6d511a48

build:
  skip: true  # [win]
  number: 0
  run_exports:
    # Each release checks the version number of the headers to make sure it matches
    - {{ pin_subpackage('vector-classes', max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - make  # [unix]

test:
  commands:
    - test -f "${PREFIX}/include/Vc/version.h"
    - test -f "${PREFIX}/lib/cmake/Vc/FindVc.cmake"
    - test -f "${PREFIX}/lib/libVc.a"

about:
  home: https://github.com/VcDevel/Vc
  license: Apache-2.0
  license_file: LICENSE
  summary: SIMD Vector Classes for C++
  description: |
    The Vc library implements portable, zero-overhead C++ types for explicitly
    data-parallel programming. The 1.x releases ship implementations for x86
    SIMD instruction sets SSE, AVX, AVX2, and the Xeon Phi (MIC). A scalar
    implementation ensures full portability to any C++11 capable compiler and
    target system.
  doc_url: https://vcdevel.github.io/Vc-{{ version }}/
  dev_url: https://github.com/VcDevel/Vc

extra:
  recipe-maintainers:
    - chrisburr
